Update up.ps1
mykolasredin/XmCloudPreview pull request #1
Opened 2022-05-24 09:25 UTC by mykolasredin

Added Login flow without UI, added parameters for required variables.

2022-05-24 11:51 UTC, AndreyPilipchenko commented on up.ps1
> +    [switch]$SilentLogin,
This variables or placeholders for them should be defined in .env file, and assigned in scrip body, not in params

2022-05-24 11:51 UTC, AndreyPilipchenko commented on up.ps1
> +$xmCloudDomain = $envContent | Where-Object { $_ -imatch "^SITECORE_FedAuth_dot_Auth0_dot_Domain=.+" }
All variables, related to client login should be defined here 

if($SilentLogin){
#define variables here
}

2022-05-24 11:51 UTC, AndreyPilipchenko commented on up.ps1
> +    dotnet sitecore cloud login --authority $xmCloudDomain --audience $xmCloudAud --client-id $AuthClientId --client-secret $AuthClientSecret --client-credentials
add --allow-write true

2022-05-24 11:51 UTC, AndreyPilipchenko commented on up.ps1
>  dotnet sitecore login --ref xmcloud --cm https://$xmCloudHost --allow-write true
move under else{}

2022-05-25 09:49 UTC, AndreyPilipchenko requested changes

2022-05-25 09:49 UTC, AndreyPilipchenko commented on .env
> +# SITECORE_FedAuth_dot_Auth0_dot_SilentLogin=false
Please change name to_ClientCredentialsLogin and also change it in script

2022-05-25 09:49 UTC, AndreyPilipchenko commented on .env
> +SITECORE_FedAuth_dot_Auth0_dot_AudienceForSilentLogin=
is it really needed? an audience should be the same for all login variants

2022-05-25 09:49 UTC, AndreyPilipchenko commented on README.md
> +    * To log in via client credentials flow, set the environment variable SITECORE_FedAuth_dot_Auth0_dot_SilentLogin to "true" and update values of the correspond environment variables (Domain, Audie
Please provide exact names of variables to update

2022-05-25 09:49 UTC, AndreyPilipchenko commented on up.ps1
> +    dotnet sitecore cloud login --authority $xmCloudDomain --audience $xmCloudAudSilentLogin --client-id $xmCloudClientId --client-secret $xmCloudClientSecret --client-credentials
please add --allow-write true

2022-05-25 09:49 UTC, AndreyPilipchenko commented on up.ps1
> +	dotnet sitecore login --ref xmcloud --cm https://$xmCloudHost --allow-write true
fix idents

2022-05-25 10:03 UTC, mykolasredin commented on .env
> +SITECORE_FedAuth_dot_Auth0_dot_AudienceForSilentLogin=
We have all variables doubled in this script, e.g., SITECORE_FedAuth_dot_Auth0_dot_IsLocal

2022-05-25 11:07 UTC, mykolasredin commented on up.ps1
> +    dotnet sitecore cloud login --authority $xmCloudDomain --audience $xmCloudAudSilentLogin --client-id $xmCloudClientId --client-secret $xmCloudClientSecret --client-credentials
The script failed, if I add this parameter.

2022-06-05 07:17 UTC, merged